name: Basic Workflow
on: [push]
jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
          with:
            ref: refs/heads/master
        - name: run an echo command
          run: echo "E da me che voi? Io te posso cantà na canzone"
